name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make test
    - name: In case of failure, make PR as failure
      if: always() # Executar mesmo se o teste falhar
      run: |
        if [ ${{ job.status }} == 'failure' ]; then
          echo "Tests failed, please try again."
          # Update PR status as "failed"
          curl -u ${{ secrets.GITHUB_TOKEN }} -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state": "failure", "context": "GitHub Actions - Testes Automatizados", "description": "Test Fail."}'
          exit 1
        fi
